### ISSUE TITLE
Definir las relaciones entre las entidades (uno a uno, uno a muchos, muchos a muchos). Yolimar Ramos

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#12]
Buenas noches, como ya tenemos la estructura de las entidades y sus atributos, ahora vamos a definir las relaciones entre las entidades por escrito (no dibujo), cada uno de nosotros va a hacer la lista de todas las relaciones necesarias para el funcionamiento de la bd. Después de que cada uno las envie, consolidaremos un solo archivo con estas relaciones y asi podremos continuar con la siguiente actividad.
@Yolimar36

**Comment by Yolimar-Somositel** [comment]
Cliente - Pedido
Relación: Uno a Muchos
Descripción: Un cliente puede realizar múltiples pedidos, pero cada pedido pertenece a un solo cliente.
 Pedido - Material Mágico
Relación: Muchos a Muchos
Descripción: Un pedido puede incluir varios materiales mágicos, y un material mágico puede ser utilizado en múltiples pedidos. Esto se puede manejar a través de una tabla intermedia, por ejemplo, "Materiales del Pedido".

Pedido - Artesano
Relación: Muchos a Uno
Descripción: Un pedido es manejado por un artesano. Sin embargo, un artesano puede estar asignado a muchos pedidos en diferentes momentos.
 
Material Mágico - Proveedor
Relación: Muchos a Uno
Descripción: Un material mágico es suministrado por un sólo proveedor, pero un proveedor puede suministrar múltiples materiales mágicos.

Pedido - Producción
Relación: Uno a Uno
Descripción: Cada pedido tiene un proceso de producción único asociado a él, desde el inicio hasta el final.
Pedido - Factura
Relación: Uno a Uno
Descripción: Cada pedido tiene una factura única generada para él.

Producto Diseñado (Diseño) - Pedido
Relación: Uno a Uno
Descripción: Cada diseño de producto corresponde a un solo pedido, aunque los diseños pueden ser reutilizados o inspirados en pedidos futuros.

Proveedor - Material Mágico
Relación: Uno a Muchos
Descripción: Un proveedor puede suministrar muchos materiales mágicos diferentes. Sin embargo, cada material mágico tiene un proveedor principal.
