### ISSUE TITLE
Definir las relaciones entre las entidades (uno a uno, uno a muchos, muchos a muchos). Leonel Daniels

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#13]
Buenas noches, como ya tenemos la estructura de las entidades y sus atributos, ahora vamos a definir las relaciones entre las entidades por escrito (no dibujo), cada uno de nosotros va a hacer la lista de todas las relaciones necesarias para el funcionamiento de la bd. Después de que cada uno las envie, consolidaremos un solo archivo con estas relaciones y asi podremos continuar con la siguiente actividad.
@Midasidh

**Comment by Midasidh** [comment]
Relación de Entidades


**Tipo de Contenido**

tipo_contenido - contenido_caja:

Relación: Uno a muchos

Descripción: Un tipo de contenido puede estar presente en varias cajas.

Clave Foránea: id_tipocontenido en la tabla contenido_caja.


**Materiales**


materiales - cajas_materiales:

Relación: Uno a muchos

Descripción: Un material puede ser utilizado en varias cajas.

Clave Foránea: id_material en la tabla cajas_materiales.

materiales - proveedores:

Relación: Muchos a uno

Descripción: Varios materiales pueden ser suministrados por un mismo proveedor.

Clave Foránea: id_proveedor en la tabla materiales.


**Artesanos**


artesanos - pedidos_artesanos:

Relación: Uno a muchos

Descripción: Un artesano puede estar asignado a varios pedidos.

Clave Foránea: id_artesano en la tabla pedidos_artesanos.
