### ISSUE TITLE
Definir las relaciones entre las entidades (uno a uno, uno a muchos, muchos a muchos). Omar Rivas

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#14]
Buenas noches, como ya tenemos la estructura de las entidades y sus atributos, ahora vamos a definir las relaciones entre las entidades por escrito (no dibujo), cada uno de nosotros va a hacer la lista de todas las relaciones necesarias para el funcionamiento de la bd. Después de que cada uno las envie, consolidaremos un solo archivo con estas relaciones y asi podremos continuar con la siguiente actividad.
@theomarbass

**Comment by theomarbass** [comment]
Buenas noches a todos, acá comparto mi definición de entidad relación.

Clientes – Pedidos
Relación: Uno a muchos
Justificación: Un cliente puede hacer muchos pedidos pero, muchos clientes no pueden realizar un pedido.
*******************************************************************************
Pedidos – Calendario de producción
Relación: uno a uno
Justificación:  Cada pedido tendrá una fecha de entrega.
********************************************************************************
Presupuesto – clientes
Relación: uno a uno
Justificación: Cada presupuesto estará dirigido a un cliente.
********************************************************************************
Marketing – redes sociales
Relación: muchos a uno
Justificación: La promoción de los productos será a cada red social.
********************************************************************************
Clientes – Contenido de las cajas
Relación: uno a muchos
Justificación: Un cliente podrá requerir distintos contenidos en su caja, pero muchos clientes no podrán obtener un solo contenido en su caja.
********************************************************************************
Presupuesto – Clientes
Relación: Muchos a uno
Justificación: Podrán facilitarse varios presupuestos a un cliente, pero muchos clientes no podrán obtener un solo presupuesto.
********************************************************************************
Clientes - Diseño
Relación: uno a muchos
Justificación: Un cliente podrá obtener necesariamente varios diseños tomando en cuenta que cada caja puede tener un contenido variado.
********************************************************************************
Pedidos – Calendario de producción:
Relación: Muchos a muchos
Justificación: Uno o varios pedidos pueden entregarse en una o varias fechas distintas.
