### ISSUE TITLE
Crear diagramas de entidad-relación (DER) para visualizar las estructuras de datos. Yolimar Ramos

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#17]
Buenas noches, como ya tenemos la estructura de las entidades, sus atributos y las relaciones entre las entidades, cada uno de nosotros va a hacer el diagrama de entidad-relación (DER). Después de que cada uno lo envie por aqui (formato jpg), consolidaremos un solo diagrama y asi podremos continuar con la siguiente actividad.
@Yolimar36

**Comment by Yolimar36** [comment]
![Diagrama Caja Mágica yolimar](https://github.com/user-attachments/assets/57d8db73-cf16-4193-9b8c-b037ecd510e7)

**Comment by Yolimar-Somositel** [comment]
https://1drv.ms/i/c/435c899ffa907157/EcJCn9iPZIdNtLhh_p45b9cBktt4d9jB-2cUAewLs0c6HQ?e=A7KBam
