### ISSUE TITLE
Crear diagramas de entidad-relación (DER) para visualizar las estructuras de datos. Ana Contreras

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#18]
Buenas noches, como ya tenemos la estructura de las entidades, sus atributos y las relaciones entre las entidades, cada uno de nosotros va a hacer el diagrama de entidad-relación (DER). Después de que cada uno lo envie por aqui (formato jpg), consolidaremos un solo diagrama y asi podremos continuar con la siguiente actividad.
@anaecontreras

**Comment by anaecontreras** [comment]
Buenas noches compañeros, anexo el diagrama de entidades y relaciones (DER).
[DER Cajas Mágicas-Aporte Ana Contreras-CI17205680.pdf](https://github.com/user-attachments/files/17693740/DER.Cajas.Magicas-Aporte.Ana.Contreras-CI17205680.pdf)
