### ISSUE TITLE
Crear diagramas de entidad-relación (DER) para visualizar las estructuras de datos. Leonel Daniels

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#19]
Buenas noches, como ya tenemos la estructura de las entidades, sus atributos y las relaciones entre las entidades, cada uno de nosotros va a hacer el diagrama de entidad-relación (DER). Después de que cada uno lo envie por aqui (formato jpg), consolidaremos un solo diagrama y asi podremos continuar con la siguiente actividad.
@Midasidh

**Comment by Midasidh** [comment]
Buenas noches, mi aporte.

[DER Cajas Mágicas-Aporte Leonel Daniels-CI26272265.pdf](https://github.com/user-attachments/files/17694959/DER.Cajas.Magicas-Aporte.Leonel.Daniels-CI26272265.pdf)
