### ISSUE TITLE
Crear diagramas de entidad-relación (DER) para visualizar las estructuras de datos. Omar Rivas

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#20]
Buenas noches, como ya tenemos la estructura de las entidades, sus atributos y las relaciones entre las entidades, cada uno de nosotros va a hacer el diagrama de entidad-relación (DER). Después de que cada uno lo envie por aqui (formato jpg), consolidaremos un solo diagrama y asi podremos continuar con la siguiente actividad.
@theomarbass

**Comment by theomarbass** [comment]
[UML Cajas.pdf](https://github.com/user-attachments/files/17786654/UML.Cajas.pdf)
