### ISSUE TITLE
Identificar las entidades principales (Tablas) y sus atributos (Campos) para el caso de estudio. Leonel Daniels

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#3]
Buenas noches @Midasidh , después de hacer el análisis inicial del caso de estudio, se determino que hay que crear 17 entidades para lograr almacenar toda la información a manejarse en nuestro caso, estas entidades las dividí entre el equipo de la siguiente manera:
Leonel Daniels:
•	tipo de contenido 
•	materiales 
•	artesanos

**Comment by Midasidh** [comment]
Buenas tardes, mi aporte.


Table tipo_contenido {
    id integer [primary key] // Clave primaria de la entidad tipo_contenido
    nombre varchar // Nombre del tipo de contenido
    descripcion text // Descripción del tipo de contenido
}

Table materiales {
    id integer [primary key] // Clave primaria de la entidad materiales
    nombre varchar // Nombre del material
    origen varchar // Origen del material
    propiedades text // Propiedades mágicas del material
    cantidad_en_stock integer // Cantidad disponible en el inventario
    id_proveedor integer // Relación con la entidad: proveedores
    precio decimal // Precio de compra del material
}

Table artesanos {
    id integer [primary key] // Clave primaria de la entidad artesanos
    nombre varchar // Nombre del artesano
    especialidad varchar // Especialidad del artesano
    contacto varchar // Información de contacto del artesano
    estado varchar // Estado del artesano: Activo, Inactivo
    }
