### ISSUE TITLE
Identificar las entidades principales (Tablas) y sus atributos (Campos) para el caso de estudio. Yolimar Ramos

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#4]
Buenas noches @Yolimar36 , después de hacer el análisis inicial del caso de estudio, se determino que hay que crear 17 entidades para lograr almacenar toda la información a manejarse en nuestro caso, estas entidades las dividí entre el equipo de la siguiente manera:
Yolimar Ramos:
•	proveedores 
•	cajas de materiales 
•	pedidos artesanos

**Comment by Yolimar36** [comment]
CREATE TABLE Proveedores (
    ID_Proveedor SERIAL PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Contacto VARCHAR(100),
    Especialidades TEXT,
    Acuerdos_Comerciales TEXT
);

SELECT * FROM proveedores;


CREATE TABLE Materiales_Magicos (
    ID_Material SERIAL PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Origen VARCHAR(100),
    Propiedades_Mágicas TEXT,
    Cantidad_Stock INT NOT NULL,
    ID_Proveedor INT,
    Precio_Compra DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_Proveedor) REFERENCES Proveedores(ID_Proveedor) ON DELETE SET NULL
);
CREATE TABLE Pedidos_Materiales (
    ID_Pedido INT NOT NULL,
    ID_Material INT NOT NULL,
    Cantidad INT NOT NULL,
    PRIMARY KEY (ID_Pedido, ID_Material),
    FOREIGN KEY (ID_Pedido) REFERENCES Pedidos(ID_Pedido) ON DELETE CASCADE,
    FOREIGN KEY (ID_Material) REFERENCES Materiales_Magicos(ID_Material) ON DELETE CASCADE
);

**Comment by Yolimar36** [comment]
CREATE TABLE Proveedores (
    ID_Proveedor SERIAL PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Contacto VARCHAR(100),
    Especialidades TEXT,
    Acuerdos_Comerciales TEXT
);

SELECT * FROM proveedores;

CREATE TABLE Materiales_Magicos (
    ID_Material SERIAL PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Origen VARCHAR(100),
    Propiedades_Mágicas TEXT,
    Cantidad_Stock INT NOT NULL,
    ID_Proveedor INT,
    Precio_Compra DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_Proveedor) REFERENCES Proveedores(ID_Proveedor) ON DELETE SET NULL
);
CREATE TABLE Artesanos (
    ID_Artesano SERIAL PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Especialidad VARCHAR(100)
);

SELECT * FROM artesanos;

**Comment by dianasierra1109** [comment]
hola

**Comment by Yolimar36** [comment]
CREATE TABLE Proveedores (
ID_Proveedor SERIAL PRIMARY KEY,
Nombre VARCHAR(100) NOT NULL,
Contacto VARCHAR(100),
Especialidades TEXT,
Acuerdos_Comerciales TEXT
);

SELECT * FROM proveedores;

CREATE TABLE Materiales_Magicos (
ID_Material SERIAL PRIMARY KEY,
Nombre VARCHAR(100) NOT NULL,
Origen VARCHAR(100),
Propiedades_Mágicas TEXT,
Cantidad_Stock INT NOT NULL,
ID_Proveedor INT,
Precio_Compra DECIMAL(10, 2) NOT NULL,
FOREIGN KEY (ID_Proveedor) REFERENCES Proveedores(ID_Proveedor) ON DELETE SET NULL
);
CREATE TABLE Pedidos_Materiales (
ID_Pedido INT NOT NULL,
ID_Material INT NOT NULL,
Cantidad INT NOT NULL,
PRIMARY KEY (ID_Pedido, ID_Material),
FOREIGN KEY (ID_Pedido) REFERENCES Pedidos(ID_Pedido) ON DELETE CASCADE,
FOREIGN KEY (ID_Material) REFERENCES Materiales_Magicos(ID_Material) ON DELETE CASCADE

**Comment by Yolimar-Somositel** [comment]
Table proveedores {
  id integer [primary key] // Clave primaria de la entidad proveedor
  nombre varchar // Nombre del proveedor
  contacto varchar // Información de contacto del proveedor
  especialidad varchar // Especialidad del proveedor en relación a materiales
  acuerdos_comerciales varchar // Acuerdos comerciales entre la fábrica y el proveedor
  estatus varchar // Estado del proveedor: Activo, Inactivo, etc.
}

Table cajas_materiales {
  id integer [primary key] // Clave primaria de la entidad cajas_materiales
  id_caja integer // Relación con la entidad: cajas
  id_material integer // Relación con la entidad: materiales
  cantidad_usada integer // Cantidad del material usado en la caja específica
}

Table pedidos_artesanos {
  id integer [primary key] // Clave primaria de la entidad pedidos_artesanos
  id_pedido integer // Relación con la entidad: pedidos
  id_artesano integer // Relación con la entidad: artesanos
  rol varchar // Rol del artesano en el pedido, Ej: Principal, Asistente
  fecha_asignacion date // Fecha de asignación del artesano al pedido
