### ISSUE TITLE
Identificar las entidades principales (Tablas) y sus atributos (Campos) para el caso de estudio. Omar Rivas

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#5]
Buenas noches @theomarbass , después de hacer el análisis inicial del caso de estudio, se determino que hay que crear 17 entidades para lograr almacenar toda la información a manejarse en nuestro caso, estas entidades las dividí entre el equipo de la siguiente manera:
Omar Rivas:
•	calendario de producción 
•	diseños 
•	presupuesto

**Comment by theomarbass** [comment]
Table calendario_produccion {
  id integer [primary key] // Clave primaria de la entidad calendario_produccion
  tarea varchar // Tarea específica de producción, Ej: Diseño, Ensamblaje, Envío
  fecha_inicio date // Fecha de inicio de la tarea
  fecha_limite date // Fecha límite de la tarea
  estado varchar // Estado de la tarea: Pendiente, En proceso, Completada
}

Table diseños {
  id integer [primary key] // Clave primaria de la entidad diseño
  nombre varchar // Nombre del diseño
  descripcion varchar // Descripción del diseño
  colores text // Colores utilizados en el diseño
  tipo varchar // Tipo de diseño, Ej: Caja básica, Caja premium
  prototipo_virtual varchar // imagen del prototipo virtual
}

Table presupuesto { 
  id integer [primary key] // Clave primaria de la entidad presupuesto
  id_pedido integer // Relación con la entidad: pedido
  total decimal // Monto total del presupuesto
}
