### ISSUE TITLE
Identificar las entidades principales (Tablas) y sus atributos (Campos) para el caso de estudio. Ana Contreras

### ISSUE THREAD

**Issue by dianasierra1109** [dianasierra1109/ITEL-INGENIERIA-TECNOLOGICA-EN-LINEA-BDOct24#6]
Buenas noches @anaecontreras , después de hacer el análisis inicial del caso de estudio, se determino que hay que crear 17 entidades para lograr almacenar toda la información a manejarse en nuestro caso, estas entidades las dividí entre el equipo de la siguiente manera:
Ana Contreras:
•	facturas 
•	marketing 
•	redes sociales 
•	pagos

**Comment by anaecontreras** [comment]
Buenas noches, envío las entidades que me corresponden:

Table facturas {
  id integer [primary key] // Clave primaria de la entidad factura
  id_pedido integer // Relación con la entidad: pedido
  fecha_emision date // Fecha de emisión de la factura
  monto_total decimal // Monto total de la factura
  estado varchar // Estado de la factura: Pendiente, Pagada, Vencida
}

Table marketing {
  id integer [primary key] // Clave primaria de la entidad marketing
  id_diseño integer // Relación con la entidad: diseño
  estrategia varchar // Estrategia de marketing digital utilizada
  fecha_inicio date // Fecha de inicio de la campaña de marketing
  fecha_fin date // Fecha de fin de la campaña de marketing
  plataforma varchar // Plataforma de marketing utilizada: Redes sociales, Email, etc.
  resultados json // Métricas de rendimiento de la campaña
}

Table redes_sociales {
  id integer [primary key] // Clave primaria de la entidad redes_sociales
  id_marketing integer // Relación con la entidad: marketing
  plataforma varchar // Plataforma de redes sociales utilizada: Facebook, Instagram, etc.
  historia_cliente text // Historias o testimonios de clientes relacionados con la campaña
  engagement integer // Número de interacciones (me gusta, compartidos, etc.) en la campaña
}
Table pagos {
  id integer [primary key] // Clave primaria de la entidad
  id_pedido integer // Relación con la entidad: pedidos
  fecha_pago date // Fecha en que se realizó el pago
  monto decimal // Monto total pagado
  metodo varchar // Método de pago: Presencial, En línea
  estado varchar // Estado del pago: Pendiente, Completado, Fallido
  referencia_pago varchar // Código de referencia del pago (transacción, factura, etc.)
  comprobante_pago varchar // Link o referencia al comprobante de pago digital, si aplica
}
